/**
 * Writes src/public-assets.generated.ts: one static `with { type: "file" }` import per
 * servable file in public/, collected into a name → path map.
 *
 * Why a generated module rather than reading public/ from disk at runtime: the desktop
 * build ships the server as a single executable produced by `bun build --compile`, and
 * inside it `import.meta.url` points at Bun's virtual filesystem, so the old
 * `../public` lookup resolves to a directory that does not exist. A `type: "file"`
 * import is the one form Bun carries across both worlds — it yields a real path when
 * run from source and an embedded path when compiled, and `Bun.file` reads either.
 *
 * A map lookup also retires the path-traversal guard the disk route needed: a request
 * either names a key that was generated from public/, or it 404s. There is no path to
 * escape from.
 *
 * Run: bun run generate:assets   (public-assets.test.ts fails if this was forgotten)
 */
import { readdir } from "node:fs/promises";
import { relative as relativePath, resolve } from "node:path";
import { servable } from "../src/public-mime.js";

const ROOT = resolve(import.meta.dir, "..");
const PUBLIC = resolve(ROOT, "public");
const OUTPUT = resolve(ROOT, "src", "public-assets.generated.ts");

/** Servable files under public/, as forward-slashed paths relative to it, sorted. */
export async function collectAssets(directory: string = PUBLIC): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true, recursive: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relativePath(PUBLIC, resolve(entry.parentPath, entry.name)).replaceAll("\\", "/"))
    .filter(servable)
    .sort();
}

export function render(assets: string[]): string {
  // Identifiers are positional rather than derived from the filename: the set contains
  // hyphens, dots and two directories deep, none of which survive as an identifier.
  const imports = assets
    .map((asset, index) => `import asset${index} from "../public/${asset}" with { type: "file" };`)
    .join("\n");
  const entries = assets.map((asset, index) => `  ${JSON.stringify(asset)}: asset${index},`).join("\n");

  // @ts-nocheck is load-bearing: tsc has no model for \`with { type: "file" }\` and
  // resolves these as modules — reporting "cannot find module" for a .woff2 and
  // "typeof import(...) is not assignable to string" for a .js. Bun is the authority
  // on this import form, and public-assets.test.ts is what verifies the result. The
  // annotated export below keeps every consumer of the map fully checked.
  return `// GENERATED by scripts/generate-public-manifest.ts — do not edit.
// Run \`bun run generate:assets\` after adding, removing or renaming a file in public/.
// @ts-nocheck — see the note in scripts/generate-public-manifest.ts
${imports}

/**
 * Served file name → a path \`Bun.file\` can read: the real one from source, the
 * embedded one inside a \`bun build --compile\` executable.
 */
export const PUBLIC_ASSETS: Record<string, string> = {
${entries}
};
`;
}

if (import.meta.main) {
  const assets = await collectAssets();
  await Bun.write(OUTPUT, render(assets));
  console.log(`  ${assets.length} assets → ${relativePath(ROOT, OUTPUT).replaceAll("\\", "/")}`);
}
