// GENERATED by scripts/generate-public-manifest.ts — do not edit.
// Run `bun run generate:assets` after adding, removing or renaming a file in public/.
// @ts-nocheck — see the note in scripts/generate-public-manifest.ts
import asset0 from "../public/api.js" with { type: "file" };
import asset1 from "../public/app.js" with { type: "file" };
import asset2 from "../public/bklit-ui/bklit.js" with { type: "file" };
import asset3 from "../public/fonts/jetbrains-mono-500-latin.woff2" with { type: "file" };
import asset4 from "../public/fonts/schibsted-var-latin.woff2" with { type: "file" };
import asset5 from "../public/fonts/syne-var-latin.woff2" with { type: "file" };
import asset6 from "../public/github-contributions.prototype.js" with { type: "file" };
import asset7 from "../public/index.html" with { type: "file" };
import asset8 from "../public/logo.svg" with { type: "file" };
import asset9 from "../public/logos/claude.png" with { type: "file" };
import asset10 from "../public/logos/codex.png" with { type: "file" };
import asset11 from "../public/logos/codex.svg" with { type: "file" };
import asset12 from "../public/logos/gemini.png" with { type: "file" };
import asset13 from "../public/logos/gemini.svg" with { type: "file" };
import asset14 from "../public/logos/moonshot.png" with { type: "file" };
import asset15 from "../public/logos/zai.svg" with { type: "file" };
import asset16 from "../public/og.jpg" with { type: "file" };
import asset17 from "../public/ui.js" with { type: "file" };
import asset18 from "../public/update.js" with { type: "file" };

/**
 * Served file name → a path `Bun.file` can read: the real one from source, the
 * embedded one inside a `bun build --compile` executable.
 */
export const PUBLIC_ASSETS: Record<string, string> = {
  "api.js": asset0,
  "app.js": asset1,
  "bklit-ui/bklit.js": asset2,
  "fonts/jetbrains-mono-500-latin.woff2": asset3,
  "fonts/schibsted-var-latin.woff2": asset4,
  "fonts/syne-var-latin.woff2": asset5,
  "github-contributions.prototype.js": asset6,
  "index.html": asset7,
  "logo.svg": asset8,
  "logos/claude.png": asset9,
  "logos/codex.png": asset10,
  "logos/codex.svg": asset11,
  "logos/gemini.png": asset12,
  "logos/gemini.svg": asset13,
  "logos/moonshot.png": asset14,
  "logos/zai.svg": asset15,
  "og.jpg": asset16,
  "ui.js": asset17,
  "update.js": asset18,
};
